import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import Header from "../components/header";

import "./globals.scss";

export const neuton = Nunito_Sans({
  weight: ["300", "600", "800"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={neuton.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
